stages:
    - test
    - build
    - deploy

run_test:
    stage: test
    image: python:3.9-slim-buster
    before_script:
        - apt-get update && apt-get install make
    script:
        - make test

build:
    stage: build
    image: python:3.9-slim-buster
    services:
        - docker:20.10.16-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"    
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS     
    script:
        - docker build -t rohit18docker/gitlab-ci-cd:python-app-06 .
        - docker push rohit18docker/gitlab-ci-cd:python-app-06

depoly:
    stage: deploy
    image: python:3.9-slim-buster
    before_script:
        - chmod 400 $SSH_KEY
    script:
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@34.227.65.219 "
            docker login -u $DOCKER_USER -p $DOCKER_PASS &&       
            docker run -d -p 5000:5000 rohit18docker/gitlab-ci-cd:python-app-06"               
